# -*- coding: utf-8 -*-
"""An Edge AI-Enabled Wearable Thermal Intelligence Framework for Early Breast Cancer Detection Using Adaptive Spatio-Temporal Learning and Bilateral Asymmetry  Reasoning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3i1XEuED5H3oyQzENsxbtGOzYnc8XWX
"""

# ==========================================================
# PART 1 : DATA LOADING + PREPROCESSING
# ==========================================================

import os
import cv2
import glob
import numpy as np
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt

import torch
import torchvision

from torch.utils.data import Dataset,DataLoader
from torchvision import transforms

from sklearn.model_selection import train_test_split

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device :",DEVICE)

# ==========================================================
# DATASET PATH
# ==========================================================

DATASET_PATH = "/content/DMR-IR"

IMG_SIZE = 224
BATCH_SIZE = 16

# ==========================================================
# IMAGE PATHS
# ==========================================================

classes = sorted(os.listdir(DATASET_PATH))

image_paths=[]
labels=[]

for idx,c in enumerate(classes):

    folder=os.path.join(DATASET_PATH,c)

    files=glob.glob(folder+"/*.png")
    files+=glob.glob(folder+"/*.jpg")
    files+=glob.glob(folder+"/*.jpeg")

    for f in files:

        image_paths.append(f)
        labels.append(idx)

print("Total Images :",len(image_paths))
print("Classes :",classes)

# ==========================================================
# Adaptive Temperature Calibration (ATC)
# ==========================================================

def adaptive_temperature_calibration(img):

    img=img.astype(np.float32)

    mn=np.min(img)
    mx=np.max(img)

    img=(img-mn)/(mx-mn+1e-8)

    img=img*255

    return img.astype(np.uint8)

# ==========================================================
# Non Local Means Denoising
# ==========================================================

def nlm_denoise(img):

    return cv2.fastNlMeansDenoising(img,None,10,7,21)

# ==========================================================
# CLAHE
# ==========================================================

def clahe(img):

    c=cv2.createCLAHE(
        clipLimit=2.0,
        tileGridSize=(8,8)
    )

    return c.apply(img)

# ==========================================================
# Thermal Intensity Normalization
# ==========================================================

def thermal_normalization(img):

    img=img.astype(np.float32)

    img=(img-img.mean())/(img.std()+1e-8)

    img=(img-img.min())/(img.max()-img.min()+1e-8)

    img*=255

    return img.astype(np.uint8)

# ==========================================================
# Simple Breast Segmentation
# ==========================================================

def segment_breast(img):

    _,mask=cv2.threshold(
        img,
        0,
        255,
        cv2.THRESH_BINARY+cv2.THRESH_OTSU
    )

    kernel=np.ones((5,5),np.uint8)

    mask=cv2.morphologyEx(
        mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    segmented=cv2.bitwise_and(img,img,mask=mask)

    return segmented

# ==========================================================
# PREPROCESS PIPELINE
# ==========================================================

def preprocess(image_path):

    img=cv2.imread(image_path,0)

    img=adaptive_temperature_calibration(img)

    img=nlm_denoise(img)

    img=clahe(img)

    img=thermal_normalization(img)

    img=segment_breast(img)

    img=cv2.resize(img,(224,224))

    img=cv2.cvtColor(img,cv2.COLOR_GRAY2RGB)

    return img

# ==========================================================
# Dataset
# ==========================================================

train_paths,test_paths,train_labels,test_labels = train_test_split(
    image_paths,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

transform=transforms.Compose([

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.5,0.5,0.5],
        std=[0.5,0.5,0.5]
    )

])

class ThermalDataset(Dataset):

    def __init__(self,paths,labels):

        self.paths=paths
        self.labels=labels

    def __len__(self):

        return len(self.paths)

    def __getitem__(self,index):

        img=preprocess(self.paths[index])

        img=transform(img)

        label=self.labels[index]

        return img,label

train_dataset=ThermalDataset(
    train_paths,
    train_labels
)

test_dataset=ThermalDataset(
    test_paths,
    test_labels
)

train_loader=DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2
)

test_loader=DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

print("Train Images :",len(train_dataset))
print("Test Images :",len(test_dataset))

# ==========================================================
# DISPLAY SAMPLE
# ==========================================================

sample,_=train_dataset[0]

sample=sample.permute(1,2,0).numpy()

sample=(sample*0.5)+0.5

plt.figure(figsize=(5,5))
plt.imshow(sample)
plt.axis("off")
plt.title("Preprocessed Thermal Image")
plt.show()

# ==========================================================
# PART 2 - SECTION 1
# ConvNeXt V2 Tiny Backbone
# ==========================================================

import torch
import torch.nn as nn
import torchvision.models as models

# ----------------------------------------------------------
# ConvNeXt Tiny Backbone
# ----------------------------------------------------------

class ConvNeXtTinyBackbone(nn.Module):

    def __init__(self):

        super().__init__()

        model = models.convnext_tiny(weights="DEFAULT")

        self.features = model.features

        self.pool = nn.AdaptiveAvgPool2d((1,1))

        self.out_channels = 768

    def forward(self,x):

        x = self.features(x)

        feature_map = x

        x = self.pool(x)

        x = torch.flatten(x,1)

        return feature_map,x

# ----------------------------------------------------------
# Test
# ----------------------------------------------------------

convnext = ConvNeXtTinyBackbone().to(DEVICE)

dummy = torch.randn(2,3,224,224).to(DEVICE)

feature_map,feature_vector = convnext(dummy)

print("="*60)
print("ConvNeXt Feature Map :",feature_map.shape)
print("ConvNeXt Feature Vector :",feature_vector.shape)
print("="*60)

!pip install -q timm

# ==========================================================
# PART 2 - SECTION 2
# Swin Transformer V2 Tiny Backbone
# ==========================================================

import timm
import torch
import torch.nn as nn

# ----------------------------------------------------------
# Swin Transformer V2 Tiny
# ----------------------------------------------------------

class SwinTransformerBackbone(nn.Module):

    def __init__(self):

        super().__init__()

        self.model = timm.create_model(
            "swinv2_tiny_window8_256",
            pretrained=True,
            num_classes=0,
            global_pool=""
        )

        self.pool = nn.AdaptiveAvgPool1d(1)

        self.out_channels = 768

    def forward(self,x):

        x = self.model.forward_features(x)

        # (B,H,W,C) -> (B,C,H,W)
        x = x.permute(0,3,1,2)

        feature_map = x

        B,C,H,W = x.shape

        x = x.reshape(B,C,-1)

        x = self.pool(x).squeeze(-1)

        return feature_map,x


# ----------------------------------------------------------
# Test
# ----------------------------------------------------------

swin = SwinTransformerBackbone().to(DEVICE)

dummy = torch.randn(2,3,224,224).to(DEVICE)

feature_map,feature_vector = swin(dummy)

print("="*60)
print("Swin Feature Map :",feature_map.shape)
print("Swin Feature Vector :",feature_vector.shape)
print("="*60)

# ==========================================================
# PART 2 - SECTION 3
# Multi-Scale Thermal Feature Pyramid (MSTFP)
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------------------------------------
# Conv Block
# ----------------------------------------------------------

class ConvBlock(nn.Module):

    def __init__(self,in_channels,out_channels):

        super().__init__()

        self.block=nn.Sequential(

            nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(out_channels),

            nn.GELU()

        )

    def forward(self,x):

        return self.block(x)

# ----------------------------------------------------------
# Multi Scale Feature Pyramid
# ----------------------------------------------------------

class MultiScaleThermalFeaturePyramid(nn.Module):

    def __init__(self,in_channels=768):

        super().__init__()

        # 1x1 Projection
        self.proj=nn.Conv2d(
            in_channels,
            256,
            kernel_size=1
        )

        # Multi-scale branches
        self.scale1=ConvBlock(256,256)

        self.scale2=nn.Sequential(

            nn.MaxPool2d(2),

            ConvBlock(256,256)

        )

        self.scale3=nn.Sequential(

            nn.MaxPool2d(4),

            ConvBlock(256,256)

        )

        self.scale4=nn.Sequential(

            nn.AdaptiveAvgPool2d(1),

            ConvBlock(256,256)

        )

        self.fusion=nn.Sequential(

            nn.Conv2d(
                1024,
                512,
                kernel_size=3,
                padding=1
            ),

            nn.BatchNorm2d(512),

            nn.GELU()

        )

    def forward(self,x):

        x=self.proj(x)

        s1=self.scale1(x)

        s2=self.scale2(x)

        s3=self.scale3(x)

        s4=self.scale4(x)

        s2=F.interpolate(
            s2,
            size=s1.shape[2:],
            mode='bilinear',
            align_corners=False
        )

        s3=F.interpolate(
            s3,
            size=s1.shape[2:],
            mode='bilinear',
            align_corners=False
        )

        s4=F.interpolate(
            s4,
            size=s1.shape[2:],
            mode='bilinear',
            align_corners=False
        )

        out=torch.cat(
            [s1,s2,s3,s4],
            dim=1
        )

        out=self.fusion(out)

        return out

# ----------------------------------------------------------
# Test
# ----------------------------------------------------------

mstfp=MultiScaleThermalFeaturePyramid().to(DEVICE)

dummy=torch.randn(
    2,
    768,
    7,
    7
).to(DEVICE)

output=mstfp(dummy)

print("="*60)
print("Multi Scale Output :",output.shape)
print("="*60)

# ==========================================================
# PART 2 - SECTION 4
# Temporal Memory Attention Module (TMAM)
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------------------------------------
# Channel Attention
# ----------------------------------------------------------

class ChannelAttention(nn.Module):

    def __init__(self, channels, reduction=16):

        super().__init__()

        self.avg_pool = nn.AdaptiveAvgPool2d(1)

        self.max_pool = nn.AdaptiveMaxPool2d(1)

        self.mlp = nn.Sequential(

            nn.Conv2d(channels, channels//reduction, 1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(channels//reduction, channels, 1, bias=False)

        )

        self.sigmoid = nn.Sigmoid()

    def forward(self,x):

        avg = self.mlp(self.avg_pool(x))

        mx = self.mlp(self.max_pool(x))

        attention = self.sigmoid(avg + mx)

        return x * attention


# ----------------------------------------------------------
# Spatial Attention
# ----------------------------------------------------------

class SpatialAttention(nn.Module):

    def __init__(self):

        super().__init__()

        self.conv = nn.Conv2d(
            2,
            1,
            kernel_size=7,
            padding=3,
            bias=False
        )

        self.sigmoid = nn.Sigmoid()

    def forward(self,x):

        avg = torch.mean(x,dim=1,keepdim=True)

        mx,_ = torch.max(x,dim=1,keepdim=True)

        attention = torch.cat([avg,mx],dim=1)

        attention = self.sigmoid(self.conv(attention))

        return x * attention


# ----------------------------------------------------------
# Temporal Memory Attention Module
# ----------------------------------------------------------

class TMAM(nn.Module):

    def __init__(self,in_channels=512):

        super().__init__()

        self.channel_attention = ChannelAttention(in_channels)

        self.spatial_attention = SpatialAttention()

        self.memory = nn.GRU(

            input_size=in_channels,

            hidden_size=in_channels,

            batch_first=True

        )

        self.output = nn.Sequential(

            nn.Conv2d(
                in_channels,
                in_channels,
                kernel_size=3,
                padding=1
            ),

            nn.BatchNorm2d(in_channels),

            nn.GELU()

        )

    def forward(self,x):

        B,C,H,W = x.shape

        x = self.channel_attention(x)

        x = self.spatial_attention(x)

        sequence = x.view(B,C,H*W)

        sequence = sequence.permute(0,2,1)

        memory,_ = self.memory(sequence)

        memory = memory.permute(0,2,1)

        memory = memory.view(B,C,H,W)

        output = self.output(memory)

        return output


# ----------------------------------------------------------
# Test
# ----------------------------------------------------------

tmam = TMAM().to(DEVICE)

dummy = torch.randn(2,512,7,7).to(DEVICE)

out = tmam(dummy)

print("="*60)
print("TMAM Output :",out.shape)
print("="*60)

# ==========================================================
# PART 2 - SECTION 5
# Adaptive Feature Aggregation Layer (AFAL)
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------------------------------------
# Adaptive Feature Aggregation Layer
# ----------------------------------------------------------

class AFAL(nn.Module):

    def __init__(self,
                 conv_channels=768,
                 swin_channels=768,
                 thermal_channels=512):

        super(AFAL,self).__init__()

        self.conv_proj = nn.Conv2d(conv_channels,256,1)

        self.swin_proj = nn.Conv2d(swin_channels,256,1)

        self.thermal_proj = nn.Conv2d(thermal_channels,256,1)

        # Adaptive Weights
        self.weight_generator = nn.Sequential(

            nn.AdaptiveAvgPool2d(1),

            nn.Conv2d(768,256,1),

            nn.ReLU(inplace=True),

            nn.Conv2d(256,3,1),

            nn.Softmax(dim=1)

        )

        # Final Fusion
        self.fusion = nn.Sequential(

            nn.Conv2d(
                256,
                512,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(512),

            nn.GELU(),

            nn.Conv2d(
                512,
                512,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(512),

            nn.GELU()

        )

        self.pool = nn.AdaptiveAvgPool2d(1)

    def forward(self,
                conv_feat,
                swin_feat,
                thermal_feat):

        conv_feat = self.conv_proj(conv_feat)

        swin_feat = self.swin_proj(swin_feat)

        thermal_feat = self.thermal_proj(thermal_feat)

        fusion_input = torch.cat(
            [conv_feat,swin_feat,thermal_feat],
            dim=1
        )

        weights = self.weight_generator(fusion_input)

        w1 = weights[:,0:1,:,:]

        w2 = weights[:,1:2,:,:]

        w3 = weights[:,2:3,:,:]

        fused = (w1*conv_feat)+(w2*swin_feat)+(w3*thermal_feat)

        fused = self.fusion(fused)

        embedding = self.pool(fused)

        embedding = torch.flatten(embedding,1)

        return fused,embedding

# ----------------------------------------------------------
# Test AFAL
# ----------------------------------------------------------

conv = torch.randn(
    2,
    768,
    7,
    7
).to(DEVICE)

swin = torch.randn(
    2,
    768,
    7,
    7
).to(DEVICE)

thermal = torch.randn(
    2,
    512,
    7,
    7
).to(DEVICE)

afal = AFAL().to(DEVICE)

feature_map,embedding = afal(
    conv,
    swin,
    thermal
)

print("="*60)
print("AFAL Feature Map :",feature_map.shape)
print("Thermal Embedding :",embedding.shape)
print("="*60)

# ==========================================================
# PART 2 - SECTION 6
# Complete AWT-STFNet
# ==========================================================

import torch
import torch.nn as nn

# ----------------------------------------------------------
# Adaptive Wearable Thermal Spatio-Temporal Feature Network
# ----------------------------------------------------------

class AWT_STFNet(nn.Module):

    def __init__(self):

        super(AWT_STFNet,self).__init__()

        # ConvNeXt Branch
        self.convnext = ConvNeXtTinyBackbone()

        # Swin Branch
        self.swin = SwinTransformerBackbone()

        # Multi-scale Thermal Feature Pyramid
        self.mstfp = MultiScaleThermalFeaturePyramid(
            in_channels=768
        )

        # Temporal Memory Attention
        self.tmam = TMAM(
            in_channels=512
        )

        # Adaptive Feature Aggregation
        self.afal = AFAL()

    def forward(self,x):

        # -----------------------------------------
        # ConvNeXt Features
        # -----------------------------------------

        conv_map,conv_vector = self.convnext(x)

        # -----------------------------------------
        # Swin Features
        # -----------------------------------------

        swin_map,swin_vector = self.swin(x)

        # -----------------------------------------
        # Thermal Pyramid
        # -----------------------------------------

        thermal_map = self.mstfp(conv_map)

        # -----------------------------------------
        # Temporal Memory Attention
        # -----------------------------------------

        thermal_map = self.tmam(thermal_map)

        # -----------------------------------------
        # Adaptive Feature Aggregation
        # -----------------------------------------

        fused_map,embedding = self.afal(

            conv_map,

            swin_map,

            thermal_map

        )

        return {

            "convnext_feature_map":conv_map,

            "convnext_embedding":conv_vector,

            "swin_feature_map":swin_map,

            "swin_embedding":swin_vector,

            "thermal_feature_map":thermal_map,

            "fusion_feature_map":fused_map,

            "embedding":embedding

        }

# ==========================================================
# Build Model
# ==========================================================

awt_model = AWT_STFNet().to(DEVICE)

print(awt_model)

# ==========================================================
# Forward Pass Test
# ==========================================================

dummy = torch.randn(

    2,

    3,

    224,

    224

).to(DEVICE)

outputs = awt_model(dummy)

print("="*60)

for k,v in outputs.items():

    print(k," : ",v.shape)

print("="*60)

# ==========================================================
# PART 3 - SECTION 1
# Bilateral Feature Decomposition Module
# ==========================================================

import torch
import torch.nn as nn

# ----------------------------------------------------------
# Bilateral Feature Decomposition
# ----------------------------------------------------------

class BilateralFeatureDecomposition(nn.Module):

    def __init__(self):

        super(BilateralFeatureDecomposition,self).__init__()

    def forward(self,x):

        """
        Input :
            x -> (B,C,H,W)

        Output :
            Left Feature
            Right Feature
        """

        B,C,H,W = x.shape

        mid = W // 2

        left = x[:,:,:,0:mid]

        right = x[:,:,:,mid:W]

        return left,right


# ----------------------------------------------------------
# Test
# ----------------------------------------------------------

feature = torch.randn(
    2,
    512,
    7,
    7
).to(DEVICE)

bfd = BilateralFeatureDecomposition().to(DEVICE)

left,right = bfd(feature)

print("="*60)
print("Input Shape :",feature.shape)
print("Left Feature :",left.shape)
print("Right Feature :",right.shape)
print("="*60)

# ==========================================================
# PART 3 - SECTION 2
# Thermal Pattern Encoder
# ==========================================================

import torch
import torch.nn as nn

class ThermalPatternEncoder(nn.Module):

    def __init__(self,in_channels=512):

        super().__init__()

        self.encoder = nn.Sequential(

            nn.Conv2d(
                in_channels,
                512,
                3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(512),

            nn.GELU(),

            nn.Conv2d(
                512,
                512,
                3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(512),

            nn.GELU()

        )

    def forward(self,x):

        return self.encoder(x)


# ----------------------------------------------------------
# Test
# ----------------------------------------------------------

encoder = ThermalPatternEncoder().to(DEVICE)

left_encoded = encoder(left)

right_encoded = encoder(right)

print("="*60)
print("Encoded Left :",left_encoded.shape)
print("Encoded Right :",right_encoded.shape)
print("="*60)

# ==========================================================
# PART 3 - SECTION 3
# Bilateral Thermal Difference Mapping
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------------------------------------
# Bilateral Thermal Difference Mapping
# ----------------------------------------------------------

class BilateralDifferenceMapping(nn.Module):

    def __init__(self, channels=512):

        super().__init__()

        self.refine = nn.Sequential(

            nn.Conv2d(
                channels,
                channels,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(channels),

            nn.GELU(),

            nn.Conv2d(
                channels,
                channels,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(channels),

            nn.GELU()

        )

    def forward(self,left,right):

        # -----------------------------------------
        # Resize to same width
        # -----------------------------------------

        if left.shape[-1] != right.shape[-1]:

            right = F.interpolate(

                right,

                size=left.shape[2:],

                mode="bilinear",

                align_corners=False

            )

        # -----------------------------------------
        # Absolute Difference
        # -----------------------------------------

        diff = torch.abs(left-right)

        # -----------------------------------------
        # Enhancement
        # -----------------------------------------

        diff = self.refine(diff)

        return diff


# ==========================================================
# Test
# ==========================================================

difference_module = BilateralDifferenceMapping().to(DEVICE)

difference = difference_module(

    left_encoded,

    right_encoded

)

print("="*60)

print("Difference Feature :",difference.shape)

print("="*60)

# ==========================================================
# PART 3 - SECTION 4
# Adaptive Thermal Symmetry Learning
# ==========================================================

class ATSL(nn.Module):

    def __init__(self, channels=512):

        super().__init__()

        self.attention = nn.Sequential(

            nn.AdaptiveAvgPool2d(1),

            nn.Conv2d(
                channels,
                channels//16,
                1
            ),

            nn.ReLU(),

            nn.Conv2d(
                channels//16,
                channels,
                1
            ),

            nn.Sigmoid()

        )

    def forward(self,diff):

        weight = self.attention(diff)

        output = diff * weight

        return output


# ==========================================================
# Test
# ==========================================================

atsl = ATSL().to(DEVICE)

symmetry_feature = atsl(difference)

print("="*60)

print("ATSL Output :",symmetry_feature.shape)

print("="*60)

# ==========================================================
# PART 3 - SECTION 5
# Cross-Attention Feature Fusion Module (CAFM)
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

class CrossAttentionFusion(nn.Module):

    def __init__(self, channels=512):

        super().__init__()

        self.query = nn.Conv2d(channels, channels//8, 1)

        self.key = nn.Conv2d(channels, channels//8, 1)

        self.value = nn.Conv2d(channels, channels, 1)

        self.softmax = nn.Softmax(dim=-1)

    def forward(self, left, right):

        # Resize if needed
        if left.shape[-1] != right.shape[-1]:

            right = F.interpolate(
                right,
                size=left.shape[2:],
                mode="bilinear",
                align_corners=False
            )

        B,C,H,W = left.shape

        Q = self.query(left).view(B,-1,H*W).permute(0,2,1)

        K = self.key(right).view(B,-1,H*W)

        V = self.value(right).view(B,C,H*W)

        attention = torch.bmm(Q,K)

        attention = self.softmax(attention)

        out = torch.bmm(
            V,
            attention.permute(0,2,1)
        )

        out = out.view(B,C,H,W)

        return out + left


# ==========================================================
# Test CAFM
# ==========================================================

cafm = CrossAttentionFusion().to(DEVICE)

fusion = cafm(left_encoded,right_encoded)

print("="*60)
print("Cross Attention Output :",fusion.shape)
print("="*60)

# ==========================================================
# Channel Spatial Attention Refinement
# ==========================================================

class ChannelSpatialAttention(nn.Module):

    def __init__(self, channels=512):

        super().__init__()

        # Channel Attention
        self.ca = nn.Sequential(

            nn.AdaptiveAvgPool2d(1),

            nn.Conv2d(channels, channels//16,1),

            nn.ReLU(),

            nn.Conv2d(channels//16, channels,1),

            nn.Sigmoid()

        )

        # Spatial Attention
        self.sa = nn.Sequential(

            nn.Conv2d(
                2,
                1,
                kernel_size=7,
                padding=3,
                bias=False
            ),

            nn.Sigmoid()

        )

    def forward(self,x):

        # Channel

        weight = self.ca(x)

        x = x * weight

        # Spatial

        avg = torch.mean(x,1,keepdim=True)

        mx,_ = torch.max(x,1,keepdim=True)

        spatial = torch.cat([avg,mx],1)

        spatial = self.sa(spatial)

        x = x * spatial

        return x


# ==========================================================
# Test
# ==========================================================

attention = ChannelSpatialAttention().to(DEVICE)

attention_feature = attention(fusion)

print("="*60)
print("Attention Output :",attention_feature.shape)
print("="*60)

# ==========================================================
# PART 3 - SECTION 7
# Complete BTACF-Net
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

class BTACFNet(nn.Module):

    def __init__(self):

        super().__init__()

        # Bilateral Decomposition
        self.decompose = BilateralFeatureDecomposition()

        # Left & Right Encoder
        self.encoder = ThermalPatternEncoder()

        # Difference Mapping
        self.diff = BilateralDifferenceMapping()

        # Adaptive Thermal Symmetry Learning
        self.atsl = ATSL()

        # Cross Attention
        self.cafm = CrossAttentionFusion()

        # Channel Spatial Attention
        self.cs_attention = ChannelSpatialAttention()

        # Final Fusion
        self.fusion = nn.Sequential(

            nn.Conv2d(
                1024,
                512,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(512),

            nn.GELU(),

            nn.Conv2d(
                512,
                512,
                kernel_size=3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(512),

            nn.GELU()

        )

        self.pool = nn.AdaptiveAvgPool2d(1)

    def forward(self,x):

        # -------------------------------------
        # Bilateral Split
        # -------------------------------------

        left,right = self.decompose(x)

        # -------------------------------------
        # Thermal Encoder
        # -------------------------------------

        left = self.encoder(left)

        right = self.encoder(right)

        # -------------------------------------
        # Difference Map
        # -------------------------------------

        difference = self.diff(left,right)

        # -------------------------------------
        # Symmetry Learning
        # -------------------------------------

        symmetry = self.atsl(difference)

        # -------------------------------------
        # Cross Attention
        # -------------------------------------

        attention = self.cafm(left,right)

        # -------------------------------------
        # Channel Spatial Refinement
        # -------------------------------------

        attention = self.cs_attention(attention)

        # -------------------------------------
        # Resize
        # -------------------------------------

        symmetry = F.interpolate(

            symmetry,

            size=attention.shape[2:],

            mode="bilinear",

            align_corners=False

        )

        # -------------------------------------
        # Fusion
        # -------------------------------------

        fusion = torch.cat(

            [attention,symmetry],

            dim=1

        )

        fusion = self.fusion(fusion)

        embedding = self.pool(fusion)

        embedding = torch.flatten(embedding,1)

        return {

            "left_feature":left,

            "right_feature":right,

            "difference_feature":difference,

            "symmetry_feature":symmetry,

            "attention_feature":attention,

            "fusion_feature":fusion,

            "embedding":embedding

        }


# ==========================================================
# Test BTACF-Net
# ==========================================================

btacf = BTACFNet().to(DEVICE)

dummy = torch.randn(

    2,

    512,

    7,

    7

).to(DEVICE)

outputs = btacf(dummy)

print("="*60)

for key,value in outputs.items():

    print(key," :",value.shape)

print("="*60)

# ==========================================================
# PART 4 - SECTION 1
# Personalized Thermal Baseline Modeling (PTBM)
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------------------------------------
# Personalized Thermal Baseline Modeling
# ----------------------------------------------------------

class PersonalizedThermalBaseline(nn.Module):

    def __init__(self,
                 feature_dim=512):

        super().__init__()

        self.baseline = nn.Sequential(

            nn.Linear(feature_dim,512),

            nn.GELU(),

            nn.Dropout(0.2),

            nn.Linear(512,512)

        )

    def forward(self,x):

        baseline = self.baseline(x)

        personalized = x + baseline

        return personalized


# ==========================================================
# Clinical Risk Memory Bank
# ==========================================================

class ClinicalRiskMemory(nn.Module):

    def __init__(self,
                 feature_dim=512,
                 memory_size=128):

        super().__init__()

        self.memory = nn.Parameter(

            torch.randn(
                memory_size,
                feature_dim
            )

        )

    def forward(self,x):

        similarity = torch.matmul(

            x,

            self.memory.t()

        )

        weight = torch.softmax(

            similarity,

            dim=1

        )

        memory_feature = torch.matmul(

            weight,

            self.memory

        )

        output = x + memory_feature

        return output


# ==========================================================
# Thermal Context Descriptor
# ==========================================================

class ThermalContextDescriptor(nn.Module):

    def __init__(self,
                 feature_dim=512):

        super().__init__()

        self.context = nn.Sequential(

            nn.Linear(feature_dim,256),

            nn.ReLU(),

            nn.Linear(256,feature_dim)

        )

    def forward(self,x):

        context = self.context(x)

        return x + context


# ==========================================================
# Personalized Thermal Profile Generator
# ==========================================================

class PersonalizedThermalProfile(nn.Module):

    def __init__(self):

        super().__init__()

        self.baseline = PersonalizedThermalBaseline()

        self.memory = ClinicalRiskMemory()

        self.context = ThermalContextDescriptor()

    def forward(self,x):

        x = self.baseline(x)

        x = self.memory(x)

        x = self.context(x)

        return x


# ==========================================================
# Test
# ==========================================================

profile = PersonalizedThermalProfile().to(DEVICE)

dummy = torch.randn(

    2,

    512

).to(DEVICE)

output = profile(dummy)

print("="*60)
print("Personalized Feature :",output.shape)
print("="*60)

# ============================================================
# PART 4 - SECTION 2
# Confidence Calibration Module (CCM)
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import brier_score_loss


# ============================================================
# Confidence Calibration Module
# ============================================================

class ConfidenceCalibrationModule:

    def __init__(self):
        self.scaler = MinMaxScaler()


    # --------------------------------------------------------
    # Confidence Score Generation
    # --------------------------------------------------------

    def generate_confidence_score(self, features):

        normalized_features = self.scaler.fit_transform(
            features.reshape(-1,1)
        )

        confidence_score = np.mean(normalized_features)

        confidence_score = np.clip(
            confidence_score,
            0,
            1
        )

        return confidence_score



    # --------------------------------------------------------
    # Uncertainty Score Calculation
    # --------------------------------------------------------

    def calculate_uncertainty(self, features):

        variance = np.var(features)

        uncertainty_score = variance / (
            variance + 1
        )

        return uncertainty_score



    # --------------------------------------------------------
    # Reliability Estimation
    # --------------------------------------------------------

    def reliability_estimation(
            self,
            confidence,
            uncertainty):

        reliability = confidence * (
            1 - uncertainty
        )

        reliability = np.clip(
            reliability,
            0,
            1
        )

        return reliability



    # --------------------------------------------------------
    # Confidence Calibration
    # --------------------------------------------------------

    def calibrate_confidence(
            self,
            features):

        confidence = self.generate_confidence_score(
            features
        )

        uncertainty = self.calculate_uncertainty(
            features
        )

        reliability = self.reliability_estimation(
            confidence,
            uncertainty
        )


        calibrated_features = np.concatenate(
            [
                features,
                [
                    confidence,
                    uncertainty,
                    reliability
                ]
            ]
        )


        return calibrated_features, {
            "Confidence Score":confidence,
            "Uncertainty Score":uncertainty,
            "Reliability Score":reliability
        }



# ============================================================
# Example Input
# (Personalized Thermal Feature Vector)
# ============================================================

thermal_features = np.array([
    0.72,
    0.65,
    0.81,
    0.55,
    0.90,
    0.76,
    0.68,
    0.88
])


# ============================================================
# Apply CCM
# ============================================================

ccm = ConfidenceCalibrationModule()


calibrated_features, confidence_results = (
    ccm.calibrate_confidence(
        thermal_features
    )
)



# ============================================================
# Display Results
# ============================================================

print("="*60)
print("Confidence Calibration Module Output")
print("="*60)


for key,value in confidence_results.items():

    print(
        f"{key}: {value:.4f}"
    )


print("\nCalibrated Feature Vector:")
print(calibrated_features)

# ============================================================
# PART 4 - SECTION 2
# Confidence Calibration Module (CCM)
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import brier_score_loss


# ============================================================
# Confidence Calibration Module
# ============================================================

class ConfidenceCalibrationModule:

    def __init__(self):
        self.scaler = MinMaxScaler()


    # --------------------------------------------------------
    # Confidence Score Generation
    # --------------------------------------------------------

    def generate_confidence_score(self, features):

        normalized_features = self.scaler.fit_transform(
            features.reshape(-1,1)
        )

        confidence_score = np.mean(normalized_features)

        confidence_score = np.clip(
            confidence_score,
            0,
            1
        )

        return confidence_score



    # --------------------------------------------------------
    # Uncertainty Score Calculation
    # --------------------------------------------------------

    def calculate_uncertainty(self, features):

        variance = np.var(features)

        uncertainty_score = variance / (
            variance + 1
        )

        return uncertainty_score



    # --------------------------------------------------------
    # Reliability Estimation
    # --------------------------------------------------------

    def reliability_estimation(
            self,
            confidence,
            uncertainty):

        reliability = confidence * (
            1 - uncertainty
        )

        reliability = np.clip(
            reliability,
            0,
            1
        )

        return reliability



    # --------------------------------------------------------
    # Confidence Calibration
    # --------------------------------------------------------

    def calibrate_confidence(
            self,
            features):

        confidence = self.generate_confidence_score(
            features
        )

        uncertainty = self.calculate_uncertainty(
            features
        )

        reliability = self.reliability_estimation(
            confidence,
            uncertainty
        )


        calibrated_features = np.concatenate(
            [
                features,
                [
                    confidence,
                    uncertainty,
                    reliability
                ]
            ]
        )


        return calibrated_features, {
            "Confidence Score":confidence,
            "Uncertainty Score":uncertainty,
            "Reliability Score":reliability
        }



# ============================================================
# Example Input
# (Personalized Thermal Feature Vector)
# ============================================================

thermal_features = np.array([
    0.72,
    0.65,
    0.81,
    0.55,
    0.90,
    0.76,
    0.68,
    0.88
])


# ============================================================
# Apply CCM
# ============================================================

ccm = ConfidenceCalibrationModule()


calibrated_features, confidence_results = (
    ccm.calibrate_confidence(
        thermal_features
    )
)



# ============================================================
# Display Results
# ============================================================

print("="*60)
print("Confidence Calibration Module Output")
print("="*60)


for key,value in confidence_results.items():

    print(
        f"{key}: {value:.4f}"
    )


print("\nCalibrated Feature Vector:")
print(calibrated_features)